name: Build and Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven 
    - name: Build with Maven
      run: mvn clean package

    - name: Upload Artifact 
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-war
        path: "/petclinic.war"

    - name: Upload Artifact
      if: success()  # Only execute if previous steps were successful
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-war
        path: "/petclinic.war"
        if-no-files-found: error  # Fail the workflow if no files are found to upload
