name: Build and Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven 
    - name: Build with Maven
      run: mvn clean package

    - name: Upload Artifact 
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-war
        path: "/petclinic.war"
  deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
        name: petclinic-war
        path: "/home/runner/work/Petclinic/Petclinic/target/"
     - name: Set up SSH
       run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa    
   
        
     - name: Deploy to EC2
       run: |
            scp -i "~/.ssh/id_rsa" -o StrictHostKeyChecking=no /home/runner/work/Petclinic/Petclinic/target/petclinic.war ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/apache-tomcat-9.0.65/webapps
